<a href="https://colab.research.google.com/github/Deepanshu-8126/Deepanshu-8126/blob/main/numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# SORTING (sort) np.sort
# Return a sorted copy of an array
import numpy as np
a=np.random.randint(1,100,15)
b=np.random.randint(1,100,24).reshape(6,4)
print(a)
print(b)

# sort
print(np.sort(a)) # aascending order sorting



[95 24 52 25 27 74 32 85 79 58 29 34 65 88 32]
[[18 28 14 76]
 [49 63 17 34]
 [34 79  6 58]
 [70 15 31  9]
 [36 91 30 34]
 [55 31 54 74]]
[24 25 27 29 32 32 34 52 58 65 74 79 85 88 95]


In [4]:
# descending order sorting
print(np.sort(a)[::-1])

[95 88 85 79 74 65 58 52 34 32 32 29 27 25 24]


In [5]:
# row wise and column wise sorting using axis
print(b)
np.sort(b,axis=0)
np.sort(b,axis=1) # column wise


[[18 28 14 76]
 [49 63 17 34]
 [34 79  6 58]
 [70 15 31  9]
 [36 91 30 34]
 [55 31 54 74]]


array([[14, 18, 28, 76],
       [17, 34, 49, 63],
       [ 6, 34, 58, 79],
       [ 9, 15, 31, 70],
       [30, 34, 36, 91],
       [31, 54, 55, 74]])

In [7]:
# 2- function np.append
print(a)
print(np.append(a,200)) # append add on the last


# for 2d array
print(np.append(b,np.ones((b.shape[0],1)),axis=1))  # row

# column
print(np.append(b,np.random.random((b.shape[0],1)),axis=1))

[95 24 52 25 27 74 32 85 79 58 29 34 65 88 32]
[ 95  24  52  25  27  74  32  85  79  58  29  34  65  88  32 200]
[[18. 28. 14. 76.  1.]
 [49. 63. 17. 34.  1.]
 [34. 79.  6. 58.  1.]
 [70. 15. 31.  9.  1.]
 [36. 91. 30. 34.  1.]
 [55. 31. 54. 74.  1.]]
[[1.80000000e+01 2.80000000e+01 1.40000000e+01 7.60000000e+01
  8.28053022e-01]
 [4.90000000e+01 6.30000000e+01 1.70000000e+01 3.40000000e+01
  6.58076515e-02]
 [3.40000000e+01 7.90000000e+01 6.00000000e+00 5.80000000e+01
  8.84334023e-01]
 [7.00000000e+01 1.50000000e+01 3.10000000e+01 9.00000000e+00
  4.00095663e-03]
 [3.60000000e+01 9.10000000e+01 3.00000000e+01 3.40000000e+01
  9.85698817e-01]
 [5.50000000e+01 3.10000000e+01 5.40000000e+01 7.40000000e+01
  2.91096206e-02]]


In [18]:
# Concatenate
# in 2d arrays use most
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [20]:
# concatenate
print(np.concatenate((c,d),axis=0)) # row concatenate 0

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [21]:
# column concatenate
print(np.concatenate((c,d),axis=1))

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


EXPAND DIMENSION NP.EXPAND_DIMS

In [38]:
# 1d to 2d to 3d
a=np.arange(15)
print(a)
print(a.shape)

# 1d to 2d
b=np.expand_dims(a,axis=0)
print(b)  #1d converted to 2d
print(b.shape)  #(1,15) 1 row 15 columns

# axis =1
c=np.expand_dims(a,axis=1)
print(c)  #(15,1) 15 row 1 column


# check shape
print(c.shape)



# this method is for column vector and row vector



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
(1, 15)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]
(15, 1)


UNIQUE FUNCTION
--- with the help of np.unique we get the unique values from an array give as parameter name np.unique

5


In [65]:
e=np.array([1,1,2,2,3,3,4,4,3,3,2,2,5,6,5,5])

print(e)
# unique
print(np.unique(e))

[1 1 2 2 3 3 4 4 3 3 2 2 5 6 5 5]
[1 2 3 4 5 6]
